# Generated by Django 3.2.5 on 2021-12-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='post',
            name='IT',
            field=models.BooleanField(default=False, verbose_name='IT'),
        ),
        migrations.AddField(
            model_name='post',
            name='arts',
            field=models.BooleanField(default=False, verbose_name='arts'),
        ),
        migrations.AddField(
            model_name='post',
            name='being_late',
            field=models.BooleanField(default=False, verbose_name='being_late'),
        ),
        migrations.AddField(
            model_name='post',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='biting_nails',
            field=models.BooleanField(default=False, verbose_name='biting_nails'),
        ),
        migrations.AddField(
            model_name='post',
            name='break_up_your_studying',
            field=models.BooleanField(default=False, verbose_name='break_up_your_studying'),
        ),
        migrations.AddField(
            model_name='post',
            name='christian',
            field=models.BooleanField(default=False, verbose_name='christian'),
        ),
        migrations.AddField(
            model_name='post',
            name='commercial',
            field=models.BooleanField(default=False, verbose_name='commercial'),
        ),
        migrations.AddField(
            model_name='post',
            name='cram_all_studying_into_one_sesssion',
            field=models.BooleanField(default=False, verbose_name='cram_all_studying_into_one_sesssion'),
        ),
        migrations.AddField(
            model_name='post',
            name='female',
            field=models.BooleanField(default=False, verbose_name='female'),
        ),
        migrations.AddField(
            model_name='post',
            name='leaving_dirty_dishes_in_the_sink',
            field=models.BooleanField(default=False, verbose_name='leaving_dirty_dishes_in_the_sink'),
        ),
        migrations.AddField(
            model_name='post',
            name='leaving_the_toilet_seat_up',
            field=models.BooleanField(default=False, verbose_name='leaving_the_toilet_seat_up'),
        ),
        migrations.AddField(
            model_name='post',
            name='leaving_the_water_running',
            field=models.BooleanField(default=False, verbose_name='leaving_the_water_running'),
        ),
        migrations.AddField(
            model_name='post',
            name='littering',
            field=models.BooleanField(default=False, verbose_name='littering'),
        ),
        migrations.AddField(
            model_name='post',
            name='loud_chewing',
            field=models.BooleanField(default=False, verbose_name='loud_chewing'),
        ),
        migrations.AddField(
            model_name='post',
            name='male',
            field=models.BooleanField(default=False, verbose_name='male'),
        ),
        migrations.AddField(
            model_name='post',
            name='muslim',
            field=models.BooleanField(default=False, verbose_name='muslim'),
        ),
        migrations.AddField(
            model_name='post',
            name='north_central',
            field=models.BooleanField(default=False, verbose_name='north_central'),
        ),
        migrations.AddField(
            model_name='post',
            name='north_east',
            field=models.BooleanField(default=False, verbose_name='north_east'),
        ),
        migrations.AddField(
            model_name='post',
            name='north_west',
            field=models.BooleanField(default=False, verbose_name='north_west'),
        ),
        migrations.AddField(
            model_name='post',
            name='other',
            field=models.BooleanField(default=False, verbose_name='other'),
        ),
        migrations.AddField(
            model_name='post',
            name='practice_effective_reading_strategies',
            field=models.BooleanField(default=False, verbose_name='practice_effective_reading_strategies'),
        ),
        migrations.AddField(
            model_name='post',
            name='science',
            field=models.BooleanField(default=False, verbose_name='science'),
        ),
        migrations.AddField(
            model_name='post',
            name='scraping_a_plate_with_a_fork_or_knife',
            field=models.BooleanField(default=False, verbose_name='scraping_a_plate_with_a_fork_or_knife'),
        ),
        migrations.AddField(
            model_name='post',
            name='smoking',
            field=models.BooleanField(default=False, verbose_name='smoking'),
        ),
        migrations.AddField(
            model_name='post',
            name='sneezing_without_covering_your_mouth',
            field=models.BooleanField(default=False, verbose_name='sneezing_without_covering_your_mouth'),
        ),
        migrations.AddField(
            model_name='post',
            name='snoring',
            field=models.BooleanField(default=False, verbose_name='snoring'),
        ),
        migrations.AddField(
            model_name='post',
            name='south_east',
            field=models.BooleanField(default=False, verbose_name='south_east'),
        ),
        migrations.AddField(
            model_name='post',
            name='south_south',
            field=models.BooleanField(default=False, verbose_name='south_south'),
        ),
        migrations.AddField(
            model_name='post',
            name='south_west',
            field=models.BooleanField(default=False, verbose_name='south_west'),
        ),
        migrations.AddField(
            model_name='post',
            name='start_with_the_most_difficult_course',
            field=models.BooleanField(default=False, verbose_name='start_with_the_most_difficult_course'),
        ),
        migrations.AddField(
            model_name='post',
            name='talking_during_a_movie',
            field=models.BooleanField(default=False, verbose_name='talking_during_a_movie'),
        ),
        migrations.AddField(
            model_name='post',
            name='talking_when_your_mouth_is_full',
            field=models.BooleanField(default=False, verbose_name='talking_when_your_mouth_is_full'),
        ),
    ]
