# Generated by Django 3.2.5 on 2022-01-02 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220102_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='break_up_your_studying',
        ),
        migrations.RemoveField(
            model_name='post',
            name='cram_all_studying_into_one_sesssion',
        ),
        migrations.RemoveField(
            model_name='post',
            name='practice_effective_reading_strategies',
        ),
        migrations.RemoveField(
            model_name='post',
            name='scraping_a_plate_with_a_fork_or_knife',
        ),
        migrations.RemoveField(
            model_name='post',
            name='start_with_the_most_difficult_course',
        ),
    ]
