# Generated by Django 3.2.5 on 2022-01-04 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220102_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='being_late',
            new_name='beinglate',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='birth_date',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='biting_nails',
            new_name='bitingnails',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='leaving_dirty_dishes_in_the_sink',
            new_name='leavingdirtydishesinthesink',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='leaving_the_toilet_seat_up',
            new_name='leavingthetoiletseatup',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='leaving_the_water_running',
            new_name='leavingthewaterrunning',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='loud_chewing',
            new_name='loudchewing',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='sneezing_without_covering_your_mouth',
            new_name='sneezingwithoutcoveringyour_mouth',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='talking_during_a_movie',
            new_name='talkingduringamovie',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='talking_when_your_mouth_is_full',
            new_name='talkingwhenyourmouthisfull',
        ),
    ]
