# Generated by Django 3.2.5 on 2022-01-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220104_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='beinglate',
            field=models.BooleanField(default=False, verbose_name='beinglate'),
        ),
        migrations.AlterField(
            model_name='post',
            name='bitingnails',
            field=models.BooleanField(default=False, verbose_name='bitingnails'),
        ),
        migrations.AlterField(
            model_name='post',
            name='leavingdirtydishesinthesink',
            field=models.BooleanField(default=False, verbose_name='leavingdirtydishesinthesink'),
        ),
        migrations.AlterField(
            model_name='post',
            name='leavingthetoiletseatup',
            field=models.BooleanField(default=False, verbose_name='leavingthetoiletseatup'),
        ),
        migrations.AlterField(
            model_name='post',
            name='leavingthewaterrunning',
            field=models.BooleanField(default=False, verbose_name='leavingthewaterrunning'),
        ),
        migrations.AlterField(
            model_name='post',
            name='loudchewing',
            field=models.BooleanField(default=False, verbose_name='loudchewing'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sneezingwithoutcoveringyour_mouth',
            field=models.BooleanField(default=False, verbose_name='sneezingwithoutcoveringyourmouth'),
        ),
        migrations.AlterField(
            model_name='post',
            name='talkingduringamovie',
            field=models.BooleanField(default=False, verbose_name='talkingduringamovie'),
        ),
        migrations.AlterField(
            model_name='post',
            name='talkingwhenyourmouthisfull',
            field=models.BooleanField(default=False, verbose_name='talkingwhenyourmouthisfull'),
        ),
    ]
