# Generated by Django 3.2.5 on 2022-01-04 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220104_0728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sneezingwithoutcoveringyour_mouth',
            new_name='sneezingwithoutcoveringyourmouth',
        ),
    ]
