# Generated by Django 3.2.5 on 2022-01-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20220104_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fields',
        ),
        migrations.AddField(
            model_name='post',
            name='IT',
            field=models.BooleanField(default=False, verbose_name='fields'),
        ),
        migrations.AddField(
            model_name='post',
            name='arts',
            field=models.BooleanField(default=False, verbose_name='fields'),
        ),
        migrations.AddField(
            model_name='post',
            name='commercial',
            field=models.BooleanField(default=False, verbose_name='fields'),
        ),
        migrations.AddField(
            model_name='post',
            name='science',
            field=models.BooleanField(default=False, verbose_name='fields'),
        ),
    ]
