# Generated by Django 3.2.5 on 2022-01-05 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0012_auto_20220105_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='AB',
            field=models.BooleanField(default=False, verbose_name='AB'),
        ),
        migrations.AddField(
            model_name='post',
            name='AD',
            field=models.BooleanField(default=False, verbose_name='AD'),
        ),
        migrations.AddField(
            model_name='post',
            name='AI',
            field=models.BooleanField(default=False, verbose_name='AI'),
        ),
        migrations.AddField(
            model_name='post',
            name='AN',
            field=models.BooleanField(default=False, verbose_name='AN'),
        ),
        migrations.AddField(
            model_name='post',
            name='BA',
            field=models.BooleanField(default=False, verbose_name='BA'),
        ),
        migrations.AddField(
            model_name='post',
            name='BN',
            field=models.BooleanField(default=False, verbose_name='BN'),
        ),
        migrations.AddField(
            model_name='post',
            name='BR',
            field=models.BooleanField(default=False, verbose_name='BR'),
        ),
        migrations.AddField(
            model_name='post',
            name='BY',
            field=models.BooleanField(default=False, verbose_name='BY'),
        ),
        migrations.AddField(
            model_name='post',
            name='CR',
            field=models.BooleanField(default=False, verbose_name='CR'),
        ),
        migrations.AddField(
            model_name='post',
            name='DL',
            field=models.BooleanField(default=False, verbose_name='DL'),
        ),
        migrations.AddField(
            model_name='post',
            name='EB',
            field=models.BooleanField(default=False, verbose_name='EB'),
        ),
        migrations.AddField(
            model_name='post',
            name='ED',
            field=models.BooleanField(default=False, verbose_name='ED'),
        ),
        migrations.AddField(
            model_name='post',
            name='EK',
            field=models.BooleanField(default=False, verbose_name='EK'),
        ),
        migrations.AddField(
            model_name='post',
            name='EN',
            field=models.BooleanField(default=False, verbose_name='EN'),
        ),
        migrations.AddField(
            model_name='post',
            name='FC',
            field=models.BooleanField(default=False, verbose_name='FC'),
        ),
        migrations.AddField(
            model_name='post',
            name='GM',
            field=models.BooleanField(default=False, verbose_name='GM'),
        ),
        migrations.AddField(
            model_name='post',
            name='IM',
            field=models.BooleanField(default=False, verbose_name='IM'),
        ),
        migrations.AddField(
            model_name='post',
            name='IT',
            field=models.BooleanField(default=False, verbose_name='IT'),
        ),
        migrations.AddField(
            model_name='post',
            name='JI',
            field=models.BooleanField(default=False, verbose_name='JI'),
        ),
        migrations.AddField(
            model_name='post',
            name='KA',
            field=models.BooleanField(default=False, verbose_name='KA'),
        ),
        migrations.AddField(
            model_name='post',
            name='KB',
            field=models.BooleanField(default=False, verbose_name='KB'),
        ),
        migrations.AddField(
            model_name='post',
            name='KG',
            field=models.BooleanField(default=False, verbose_name='KG'),
        ),
        migrations.AddField(
            model_name='post',
            name='KN',
            field=models.BooleanField(default=False, verbose_name='KN'),
        ),
        migrations.AddField(
            model_name='post',
            name='KS',
            field=models.BooleanField(default=False, verbose_name='KS'),
        ),
        migrations.AddField(
            model_name='post',
            name='KW',
            field=models.BooleanField(default=False, verbose_name='KW'),
        ),
        migrations.AddField(
            model_name='post',
            name='LA',
            field=models.BooleanField(default=False, verbose_name='LA'),
        ),
        migrations.AddField(
            model_name='post',
            name='NA',
            field=models.BooleanField(default=False, verbose_name='NA'),
        ),
        migrations.AddField(
            model_name='post',
            name='NI',
            field=models.BooleanField(default=False, verbose_name='NI'),
        ),
        migrations.AddField(
            model_name='post',
            name='OG',
            field=models.BooleanField(default=False, verbose_name='OG'),
        ),
        migrations.AddField(
            model_name='post',
            name='ON',
            field=models.BooleanField(default=False, verbose_name='ON'),
        ),
        migrations.AddField(
            model_name='post',
            name='OS',
            field=models.BooleanField(default=False, verbose_name='OS'),
        ),
        migrations.AddField(
            model_name='post',
            name='OY',
            field=models.BooleanField(default=False, verbose_name='OY'),
        ),
        migrations.AddField(
            model_name='post',
            name='PT',
            field=models.BooleanField(default=False, verbose_name='PT'),
        ),
        migrations.AddField(
            model_name='post',
            name='RV',
            field=models.BooleanField(default=False, verbose_name='RV'),
        ),
        migrations.AddField(
            model_name='post',
            name='ST',
            field=models.BooleanField(default=False, verbose_name='ST'),
        ),
        migrations.AddField(
            model_name='post',
            name='TB',
            field=models.BooleanField(default=False, verbose_name='TB'),
        ),
        migrations.AddField(
            model_name='post',
            name='YB',
            field=models.BooleanField(default=False, verbose_name='YB'),
        ),
        migrations.AddField(
            model_name='post',
            name='ZF',
            field=models.BooleanField(default=False, verbose_name='ZF'),
        ),
        migrations.AddField(
            model_name='post',
            name='arts',
            field=models.BooleanField(default=False, verbose_name='arts'),
        ),
        migrations.AddField(
            model_name='post',
            name='beinglate',
            field=models.BooleanField(default=False, verbose_name='beinglate'),
        ),
        migrations.AddField(
            model_name='post',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='bitingnails',
            field=models.BooleanField(default=False, verbose_name='bitingnails'),
        ),
        migrations.AddField(
            model_name='post',
            name='christianity',
            field=models.BooleanField(default=False, verbose_name='christianity'),
        ),
        migrations.AddField(
            model_name='post',
            name='commercial',
            field=models.BooleanField(default=False, verbose_name='commercial'),
        ),
        migrations.AddField(
            model_name='post',
            name='female',
            field=models.BooleanField(default=False, verbose_name='female'),
        ),
        migrations.AddField(
            model_name='post',
            name='leavingdirtydishesinthesink',
            field=models.BooleanField(default=False, verbose_name='leavingdirtydishesinthesink'),
        ),
        migrations.AddField(
            model_name='post',
            name='leavingthetoiletseatup',
            field=models.BooleanField(default=False, verbose_name='leavingthetoiletseatup'),
        ),
        migrations.AddField(
            model_name='post',
            name='leavingthewaterrunning',
            field=models.BooleanField(default=False, verbose_name='leavingthewaterrunning'),
        ),
        migrations.AddField(
            model_name='post',
            name='littering',
            field=models.BooleanField(default=False, verbose_name='littering'),
        ),
        migrations.AddField(
            model_name='post',
            name='loudchewing',
            field=models.BooleanField(default=False, verbose_name='loudchewing'),
        ),
        migrations.AddField(
            model_name='post',
            name='male',
            field=models.BooleanField(default=False, verbose_name='male'),
        ),
        migrations.AddField(
            model_name='post',
            name='muslim',
            field=models.BooleanField(default=False, verbose_name='muslim'),
        ),
        migrations.AddField(
            model_name='post',
            name='other',
            field=models.BooleanField(default=False, verbose_name='other'),
        ),
        migrations.AddField(
            model_name='post',
            name='science',
            field=models.BooleanField(default=False, verbose_name='science'),
        ),
        migrations.AddField(
            model_name='post',
            name='smoking',
            field=models.BooleanField(default=False, verbose_name='smoking'),
        ),
        migrations.AddField(
            model_name='post',
            name='sneezingwithoutcoveringyourmouth',
            field=models.BooleanField(default=False, verbose_name='sneezingwithoutcoveringyourmouth'),
        ),
        migrations.AddField(
            model_name='post',
            name='snoring',
            field=models.BooleanField(default=False, verbose_name='snoring'),
        ),
        migrations.AddField(
            model_name='post',
            name='talkingduringamovie',
            field=models.BooleanField(default=False, verbose_name='talkingduringamovie'),
        ),
        migrations.AddField(
            model_name='post',
            name='talkingwhenyourmouthisfull',
            field=models.BooleanField(default=False, verbose_name='talkingwhenyourmouthisfull'),
        ),
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
